# Generated by Django 5.2 on 2025-06-12 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeFile',
            fields=[
                ('ResumeFileID', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('FilePath', models.CharField(db_column='file_path', max_length=512)),
                ('Status', models.CharField(db_column='status', max_length=50)),
                ('IsSelected', models.BooleanField(db_column='IsSelected', default=False)),
                ('UploadedAt', models.DateTimeField(auto_now_add=True, db_column='uploaded_at')),
                ('UpdatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('UserID', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resume File',
                'verbose_name_plural': 'Resume Files',
                'db_table': 'ResumeFile',
                'ordering': ['-UploadedAt'],
            },
        ),
    ]
