# Generated by Django 5.2 on 2025-06-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumefile',
            name='FilePath',
            field=models.FileField(db_column='FilePath', max_length=512, upload_to='resumes/%Y/%m/%d/'),
        ),
    ]
