# Generated by Django 5.2 on 2025-06-16 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_resumefile_filepath'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedData',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('Data', models.JSONField(db_column='data')),
                ('ParsedAt', models.DateTimeField(auto_now_add=True, db_column='parsed_at')),
                ('ResumeID', models.ForeignKey(db_column='resume_file_id', on_delete=django.db.models.deletion.CASCADE, related_name='parsed_data', to='profiles.resumefile')),
            ],
            options={
                'verbose_name': 'Parsed Data',
                'verbose_name_plural': 'Parsed Data',
                'db_table': 'ParsedData',
                'ordering': ['-ParsedAt'],
            },
        ),
    ]
