# Generated by Django 5.2 on 2025-05-01 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permission_id', models.AutoField(db_column='PermissionID', primary_key=True, serialize=False)),
                ('permission_name', models.CharField(db_column='PermissionName', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'Permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(db_column='RoleID', primary_key=True, serialize=False)),
                ('role_name', models.CharField(db_column='RoleName', max_length=100)),
                ('role_description', models.TextField(db_column='RoleDescription')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('users_id', models.AutoField(db_column='UsersID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='FirstName', max_length=150)),
                ('last_name', models.CharField(db_column='LastName', max_length=150)),
                ('email', models.EmailField(db_column='Email', max_length=254, unique=True)),
                ('username', models.CharField(db_column='Username', max_length=150, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=128)),
                ('status', models.CharField(db_column='Status', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('soft_delete', models.BooleanField(db_column='Soft_delete', default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('role_permission_id', models.AutoField(db_column='RolePermissionID', primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(db_column='PermissionID', on_delete=django.db.models.deletion.CASCADE, to='authx.permission')),
                ('role', models.ForeignKey(db_column='RoleID', on_delete=django.db.models.deletion.CASCADE, to='authx.role')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'RolePermission',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='UsersRole',
            fields=[
                ('user_role_id', models.AutoField(db_column='UserRoleID', primary_key=True, serialize=False)),
                ('role', models.ForeignKey(db_column='RoleID', on_delete=django.db.models.deletion.CASCADE, to='authx.role')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to='authx.user')),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'db_table': 'UsersRole',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
