# Generated by Django 5.2 on 2025-06-11 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0003_company_companyuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=50, null=True)),
                ('location', models.CharField(blank=True, db_column='location', max_length=255, null=True)),
                ('avatar', models.CharField(blank=True, db_column='avatar', max_length=255, null=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='authx.user')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'UserProfile',
            },
        ),
    ]
