# Generated by Django 5.2 on 2025-06-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0005_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='Description',
            field=models.TextField(db_column='Description', null=True),
        ),
    ]