"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
import environ
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_PATH = os.path.join(BASE_DIR, 'static')
# Initialize django-environ
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# read .env file
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Where uploaded media files are stored
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL  = '/media/'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-v-=n0vohvaq3_7@fl6w!cduugpvgemf#hwa=gtzl!fqj9giyn%'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")

# SECURITY
SECRET_KEY = env("SECRET_KEY")
DEBUG = env("DEBUG")



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "apps.common",  
    "apps.authx.apps.AuthxConfig",
    "apps.profiles.apps.ProfilesConfig",
    "apps.jobposts.apps.JobpostsConfig",
     'widget_tweaks',
     'debug_toolbar',
     'markdownify',
]

MIDDLEWARE = [
    
    
    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.authx.middleware.PermissionRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',  
    'whitenoise.middleware.WhiteNoiseMiddleware',
    
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates"],  
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "config.context_processors.site_name",
                'config.context_processors.sidebar_menu',
                "django.template.context_processors.tz"
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
# PASSWORD_HASHERS = (
#     'django.contrib.auth.hashers.PBKDF2PasswordHasher',
#     'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
#     'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
#     'django.contrib.auth.hashers.BCryptPasswordHasher',
#     'django.contrib.auth.hashers.MD5PasswordHasher',
# )


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'smartcv'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'Rasu1991'),
        'HOST': os.environ.get('DB_HOST', 'db'),
        'PORT': os.environ.get('DB_PORT', '3306'),
    }
}

if not DEBUG:
    INSTALLED_APPS += ["storages"]
    AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = env("AWS_S3_REGION_NAME")
    AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE ='whitenoise.storage.CompressedManifestStaticFilesStorage'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#ac02c1e47fa13baf1ae92ba16ec9a01c - mailtrap
# 1) Use the SMTP backend
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# 2) Mailtrap (or your SMTP) credentials
EMAIL_HOST = 'sandbox.smtp.mailtrap.io'
EMAIL_HOST_USER = '223d95ec7ae7ac'
EMAIL_HOST_PASSWORD = 'fe97c5ecd6bd9c'
EMAIL_PORT = '2525'
# 3) Default “from” address
DEFAULT_FROM_EMAIL = 'smtp@mailtrap.io'

# Only show toolbar on these internal IPs (adjust as needed)
INTERNAL_IPS = [
    '127.0.0.1',
    'localhost',
    # if you’re in Docker or VM, add your host IP here
]

SITE_NAME = "SmartCV"

# Where to redirect for @login_required and LoginRequiredMixin
LOGIN_URL          = '/auth/login/'
LOGIN_REDIRECT_URL = '/'       # After login, go here
LOGOUT_REDIRECT_URL= '/auth/login/'
AUTH_USER_MODEL = 'authx.User'
# Session settings (you can adjust as you like):
SESSION_COOKIE_AGE     = 14 * 24 * 60 * 60   # two weeks
SESSION_SAVE_EVERY_REQUEST = True

LOGGING = {
  'version': 1,
  'handlers': {
    'console': {'class': 'logging.StreamHandler'},
  },
  'loggers': {
    # catch mail backend logs
    'django.core.mail': {
      'handlers': ['console'],
      'level': 'DEBUG',
      'propagate': True,
    },
  },
}

SIDEBAR_MENU = {
    'recruiter': [
        { 'label': 'Manage Jobs',     'url_name': 'jobposts:list'      },
    ],
    'candidate': [
        { 'label': 'Search Jobs',      'url_name': 'jobposts:search'        },
        { 'label': 'My Applications',  'url_name': 'jobposts:my_applications'},
        { 'label': 'Saved Jobs',       'url_name': 'jobposts:saved_jobs'     },
        { 'label': 'My Resume',        'url_name': 'profiles:resume'         },
    ],
    'company hr': [
        { 'label': 'Company Profile',  'url_name': 'company:overview'   },
        { 'label': 'Onboard Talent',   'url_name': 'company:onboard'    },
        { 'label': 'Job Listing',      'url_name': 'jobposts:list'      },
        { 'label': 'Post New Vacancy', 'url_name': 'jobposts:create'    },
    ],
}

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


