# Generated by Django 5.2 on 2025-06-12 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('JobPostID', models.AutoField(db_column='JobPostID', primary_key=True, serialize=False)),
                ('Title', models.CharField(db_column='Title', max_length=255)),
                ('Description', models.TextField(db_column='Description')),
                ('RequiredSkills', models.TextField(db_column='RequiredSkills')),
                ('Location', models.CharField(db_column='Location', max_length=255)),
                ('EmploymentType', models.CharField(blank=True, choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('CT', 'Contract'), ('IN', 'Internship')], db_column='EmploymentType', default='FT', max_length=2)),
                ('MinSalary', models.IntegerField(blank=True, db_column='MinSalary', null=True)),
                ('MaxSalary', models.IntegerField(blank=True, db_column='MaxSalary', null=True)),
                ('RemoteOption', models.CharField(choices=[('Onsite', 'On-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], db_column='RemoteOption', max_length=6)),
                ('Industry', models.CharField(blank=True, db_column='Industry', max_length=100, null=True)),
                ('ExperienceLevel', models.CharField(blank=True, choices=[('Entry', 'Entry'), ('Mid', 'Mid'), ('Senior', 'Senior'), ('Dir', 'Director')], db_column='ExperienceLevel', default='BA', max_length=6)),
                ('EducationLevel', models.CharField(blank=True, choices=[('HS', 'High School'), ('BA', 'Bachelor’s'), ('MA', 'Master’s'), ('PhD', 'PhD')], db_column='EducationLevel', max_length=3, null=True)),
                ('ApplicationDeadline', models.DateField(blank=True, db_column='ApplicationDeadline', null=True)),
                ('Benefits', models.TextField(blank=True, db_column='Benefits', null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('UpdatedAt', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('IsActive', models.BooleanField(db_column='IsActive', default=True)),
                ('Recruiter', models.ForeignKey(db_column='RecruiterID', on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Post',
                'verbose_name_plural': 'Job Posts',
                'db_table': 'JobPost',
                'ordering': ['-CreatedAt'],
            },
        ),
        migrations.CreateModel(
            name='UserJob',
            fields=[
                ('UserJobID', models.AutoField(db_column='UserJobID', primary_key=True, serialize=False)),
                ('IsApplied', models.BooleanField(db_column='IsApplied', default=False)),
                ('IsSaved', models.BooleanField(db_column='IsSaved', default=False)),
                ('IsUnapplied', models.BooleanField(db_column='IsUnapplied', default=False)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('SoftDelete', models.BooleanField(db_column='SoftDelete', default=False)),
                ('DeletedAt', models.DateTimeField(blank=True, db_column='DeletedAt', null=True)),
                ('JobPost', models.ForeignKey(db_column='JobPostID', on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='jobposts.jobpost')),
                ('User', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='user_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User–Job Link',
                'verbose_name_plural': 'User–Job Links',
                'db_table': 'UserJob',
                'indexes': [models.Index(fields=['User'], name='ix_userjob_user'), models.Index(fields=['JobPost'], name='ix_userjob_job')],
                'constraints': [models.UniqueConstraint(fields=('User', 'JobPost'), name='uq_userjob_user_job')],
            },
        ),
    ]
